cocina_carnivora/urls.py
from django.contrib import admin
from django.urls import path, include
from cocina_carnivora import settings
from useraccount import urls
from homepage import urls
from recipes import urls
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('accounts/', include('useraccount.urls')),
    path('recipe/',include('recipes.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.home, name='home'),
 
]

recipes/urls.py
from django.urls import path
from . import views


urlpatterns =[
    path('register/', views.create_recipe, name='create_recipe'),
    path('all_recipes/', views.get_all_recipes, name='get_recipes'),
    path('recipe_detail/<int:id>', views.recipe_details, name='detail_recipe')
]

useraccount/urls.py
from django.urls import path
from .views import UserEditView, PwdChangeView, UserEditExtendedView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'useraccount'
urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.login_doggy, name='login'),
    path('password', PwdChangeView.as_view(template_name='registration/password.html'),name='password'),
    path('pwdsuccess', views.pwdsuccess, name='pwdsuccess'),
    path('<int:pk>', views.assign_role, name='assign_role'),
    path('logout',views.logout_doggy,name='logout'),
    path('editpro', UserEditView.as_view(), name='editpro'),

    path('password', PwdChangeView.as_view(template_name='registration/password.html'), name='password'),
    path('editprofile/<int:pk>/', UserEditExtendedView.as_view(), name='editprofile'), 
   
]

homepage/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User


# Create your views here.
def home(request):
    
    user_role = "Invitado"
    
    result_set = ""
    if result_set:
        user_role = "Cuidador"
    
    result_set = "*"
    if result_set:
        user_role = "Dueño"   
        
    return render(request, 'homepage/index.html', {'role': user_role })

homepage/templates/homepage/base.html
    {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <title>
    {% block title %}
    {% endblock %}
   </title> 
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <script src="{% static 'JS/script.js' %}"></script>
    
</head>
 
<body>
    <div class= "mw-100">
  
  {% include "homepage/navbar.html" %}
  {% include "messages.html" %}
    {% block content %}

     <!-- LOGICA DE LAS DEMAS VISTAS -->

    {% endblock %}
    
  {% include "homepage/footer.html" %}
   </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</body>
</html>

homepage/templates/homepage/footer.html
{% load static %}
   <footer>
          <div class="container-fluid text-white p-5" style="background-color:#926911" >
            <div class="mx-auto">
            <!-- cocina carnivora  menu-->
            <div class="row">
              <div class="col-md-4">
                <div class="mw-100">
                  <div class="text-left py-2">
                    <h5>Cocina Carnivora</h5>
                  </div>
                <ul style="list-style: none; margin:0; padding: 0;">
                  <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'home' %}">Inicio</a></li>
	         <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="#">Ayuda</a></li>

        {% if user.is_authenticated %}
         
          {% if 'Cuidador' in role %}
	           <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="#"></a></li>
	                   

          {% endif %}  
          
          {% if 'Dueño' in role %}
	
	           <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'get_recipes' %}">Ver recetas</a></li>
	  {% endif %}
         
          {% if 'Invitado' in role %}
          
	           <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="#">Ver recetas</a></li>
	           <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="#">Convertirse en cuidador</a></li>
	           <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="#">Registrar canino</a></li>

	  {% endif %}  

        {% else %}
	  
	<li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="#">Ver recetas</a></li>
	
	<li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'useraccount:login' %}">Iniciar sesion</a></li>
	
      
             <li class="py-2"><a style="text-decoration:none; color: aliceblue;" href="{% url 'useraccount:register' %}">Registrarme</a></li>
         
        

	{% endif %}
                </ul>
                </div>
              </div>
              <div class="col-md-4 ">
                <div class="text-left py-2">
                  <h5>Terminos y Condiciones</h5>
                  <h6 class="py-2">Politicas de privacidad</h6>
                </div>
                <div class="container-fluid ">
                  <!-- redes sociales -->
                  <div class="row">
                    <div class="col-4">
                      <!-- <a href="#"><img src=""> </a> -->
                   </div>
                    <div class="col-4">
                      <!-- <a href="#"><img src="#"> </a> -->
                    </div>
                    <div class="col-4">
                      <!-- <a href="#"><img src="#"> </a> -->
                    </div>
                </div>
              </div>
          </div>
          <div class="col-md-4 text-left py-2">
            <h5>Descarga nuestra aplicacion</h5>
	    
          </div>
        </div>
           
      </footer>
    

homepage/templates/homepage/index.html
{% extends "homepage/base.html" %}
{% load static %}
{% block title %}
    Cocina carnivora
{% endblock %}
{% block content %}


	      
  <img class="img-fluid h-30 w-100" src="{% static 'img/beef_home.jpg' %}" alt="">

      {% if user.is_authenticated %}
    <!--========================================================== -->
		<!-- Pantalla de Bienvenida-->
    <!--========================================================== -->
<div class="container h-100 mb-5" style="width: 80%;">

     <div class="row mt-4">
       <h3> Bienvenido/a <span style="color: #6b8cff;">{{user.username}}</span></h3>
    </div>

<div class="row mt-2 p-2">
	    <h5> Ya podés:</h5>
    </div>

    <div class="row mt-3">
      <div class="col-md-1 col-sm-12">
       <img class="p-2" src="{% static 'img/numero_1.png' %}">
      </div>

<div class="col-md-3 col-sm-12">
  <div class="row p-2">
          <a class="nav-link" href="#">
	<h5>Crear recetas</h5>
	    </a>
      </div>
      <div class="row py-2">
	  <p> Tienes una receta que no tenemos en el sitio ? publica tus propias recetas y comportila con miles de usuarios.</p>
      </div>
</div>
<div class="col-md-1 col-sm-12">
  <img class="p-2" src="{% static 'img/numero_2.png' %}">

</div>

<div class="col-md-3 col-sm-12">
  <div class="row p-2">
          <a class="nav-link" href="#">
	<h5>Leer recetas de otros</h5>
	    </a>
    </div>
  <div class="row py-2">
	<p>Ya estas listo(a) para crear deliciosas comidas a partir de recetas de otros usuarios de nuestra comunidad</p>
      </div>
</div>

<!-- <div class="col-md-1 col-sm-12">
	<img class="p-2" src="{% static 'img/numero_3.png' %}">
</div> -->

<!-- <div class="col-lg-3 col-sm-12">

  <div class="row p-2">
          <a class="nav-link" href="#">
	  <h5>Buscar hospedaje para tu perro</h5>
	    </a>
      </div>
    <div class="row py-2">
	<p>Encontrá al cuidador adecuado para tu perro y paga on-line para contar con la cobertura veterinaria.</p>
    </div>
</div> -->

</div>

</div>




        {% else %}
    <!--========================================================== -->
		<!-- ¿Cómo funciona? Y ¿ Por Qué Carn?-->
    <!--========================================================== -->
  <div class="container h-100" style="width: 80%;">

    <div class="row mt-4 p-2">
	    <h3>¿Cómo funciona Cocina carnivora?</h3>
    </div>

    <div class="row mt-3">
      <div class="col-md-1 col-sm-12">
       <img class="p-2" src="{% static 'img/numero_1.png' %}">
      </div>

<div class="col-md-3 col-sm-12">
  <div class="row p-2">
	<h5>Registrate</h5>
      </div>
      <div class="row p-2">
	  <p>Registrate como primer paso para comenzar a disfrutar de nuestro amplio catalogo de recetas</p>
      </div>
</div>
<div class="col-md-1 col-sm-12">
  <img class="p-2" src="{% static 'img/numero_2.png' %}">

</div>

<div class="col-md-3 col-sm-12">
  <div class="row p-2">
	<h5>Busca recetas</h5>
    </div>
  <div class="row p-2">
	<p>Encuentra las mejores recetas de carnes de todo internet.</p>
      </div>
</div>

<div class="col-md-1 col-sm-12">
	<img class="p-2" src="{% static 'img/numero_3.png' %}">
</div>

<div class="col-lg-3 col-sm-12">

  <div class="row">
	  <h5>Sigue los pasos</h5>
      </div>
    <div class="row">
	<p>Sigue los pasos de cada una de nuestras recetas y crea platos increibles</p>
    </div>
</div>

</div>

</div>



  <div class="container" style="width: 80%;">

<div class="row mt-4 p-2">
	<h3>¿Por qué Cocina carnivora?</h3>
</div>

<div class="row mt-3">
<div class="col-md-1 col-sm-12">
  <img class="p-2" src="{% static 'img/beneficio.png' %}">
</div>

<div class="col-md-3 col-sm-12">
  <div class="row p-2">
	<h5>Beneficios para tu cocina</h5>
      </div>
      <div class="row p-2">
	<ul>
	  <li>Cada dia son mas recetas las que se publican</li>
	  <li>Diversifica tu dieta y estilo de comidas</li>
	  

	</ul>	
      </div>
</div>
<div class="col-md-1 col-sm-12">
  <img class="p-2" src="{% static 'img/beneficio.png' %}">

</div>

<div class="col-md-3 col-sm-12">
  <div class="row p-2">
	<h5>Beneficios para vos</h5>
    </div>
  <div class="row p-2">
	<ul>
	  <li>+15.000 recetas creadas</li>
	  
	</ul>	


      </div>
</div>

<div class="col-md-1 col-sm-12">
  <img class="p-2" src="{% static 'img/beneficio.png' %}">
  
</div>

<div class="col-md-3 col-sm-12">

  <div class="row">
	  <h5>Tranquilidad</h5>
      </div>
    <div class="row">
	<ul>
	  <li>Resuelve tus comidas de manera sencilla</li>
	  <li>Te sobrara el tiempo para invertir en otras recetas</li>
	  

	</ul>	
    </div>
</div>
</div>
</div>

        {% endif %}
    

    <!--========================================================== -->
		<!-- Preguntas Frecuentes -->
    <!--========================================================== -->



  <div class="container p-4 my-5 min-vh-100 w-74">

<div class="mt-4 p-2 text-center">
  <h3 class="font-weight-bold">Preguntas Frecuentes (FAQ)</h3>
</div>

<ul>  <div class="p-2">
  <li><h5 class="font-weight-bold">¿Porque elegi cocina carnivora?</h5> </li>	
    </div>
    <div>
  <p class="text-justify"> Restaura la energía y regula el sueño
    Aumenta la tolerancia al dolor
    Mejora la concentración y el estado de ánimo,
    Reduce el estrés, fortalece y facilita el sistema digestivo,
    Las dietas ricas en grasas aumentan los niveles de testosterona
    Quizás algunos de los hechos te sorprendieron, porque es seguro decir que este tipo de dieta afecta al cuerpo humano como algunos medicamentos o productos farmacéuticos.
    Pérdida de peso
    Desintoxicación
    Equilibrar el nivel de pH del cuerpo.
    Mejor digestión y eliminación de trastornos gastrointestinales.
    Fortalecimiento de la función inmune del cuerpo.
    Mejorar el estado de ánimo
    Aumento de los niveles de energía
    Mejor estado de la piel y el cutis
    Necesitas desintoxicarte si notas uno o más de los siguientes síntomas:
    Fatiga inexplicable que dura mucho tiempo, incluso después de dormir lo suficiente
    Mal funcionamiento del sistema digestivo – flatulencia, estreñimiento, diarrea
    Irritación de la piel: eccema, erupciones cutáneas, piel seca
    Reacciones alérgicas
    Signos de inmunidad débil (infecciones repetidas)
    Ojos hinchados
    Acidez estomacal y flatulencia frecuente.
    Retención de agua
    Deterioro de la atención e incapacidad para concentrarse.
    Sensación de irritación, nerviosismo.
    Cambios de humor frecuentes
    Inestabilidad emocional, apatía, falta de motivación para el trabajo, falta de energía y
    entusiasmo por la vida
    Todos los síntomas enumerados, que a menudo consideramos temporales, son una indicación de que su cuerpo no está funcionando como debería y que necesita una desintoxicación.

</p>
    </div>
<ul>  <div class="p-2">
    <li><h5 class="font-weight-bold">¿Qué tipos de carne se pueden usar en estas recetas?</h5> </li>	
      </div>
      <div>
	  <p class="text-justify">Dependiendo de la receta, se pueden usar diferentes tipos de carne, como pollo, cerdo, ternera, cordero, pato, conejo, etc. También se pueden utilizar diferentes cortes de carne, como filetes, lomo, chuletas, etc.
	</p>
      </div>

  <div class="p-2">
	<li><h5 class="font-weight-bold">¿Cómo se deben preparar y cocinar los diferentes cortes de carne?</h5></li>	
      </div>
      <div>
	<p class="text-justify">La forma en que se deben preparar y cocinar los diferentes cortes de carne depende del tipo de carne y del corte en particular. Algunos cortes de carne, como el lomo y el filete, se pueden cocinar a altas temperaturas durante cortos períodos de tiempo para obtener un resultado rojo y jugoso. Otros cortes, como el paletilla y el guisote, se deben cocinar a temperaturas más bajas durante períodos más largos para obtener un resultado más tierno. Es importante seguir las instrucciones de la receta y utilizar un termómetro de cocina para asegurarse de que la carne se cocine a la temperatura adecuada.
	    
	</p>
      </div>


  <div class="p-2">
	<li><h5 class="font-weight-bold">¿Cuáles son las mejores técnicas de cocción para diferentes tipos de carne?</h5></li>	
      </div>
      <div class="">
	<p class=""text-justify>Algunas de las mejores técnicas de cocción para diferentes tipos de carne incluyen:

    Asado: se trata de cocinar la carne en un horno o en la parrilla a altas temperaturas durante cortos períodos de tiempo. El asado es ideal para cortes gruesos y tiernos como el lomo y el filete.
    
    Estofado: se trata de cocinar la carne en una cacerola a fuego lento con suficiente líquido para que quede tierna. El estofado es ideal para cortes más duros y menos tiernos como el guisote y la paletilla.
    
    A la parrilla: se trata de cocinar la carne en una parrilla a fuego medio o alto durante cortos períodos de tiempo. La parrilla es ideal para cortes gruesos y tiernos como el lomo y el filete.
    
    A la plancha: se trata de cocinar la carne en una sartén caliente durante cortos períodos de tiempo. La plancha es ideal para cortes delgados y tiernos como el filete y el lomo.
    
    A la brasa: se trata de cocinar la carne en una parrilla a fuego lento durante períodos más largos de tiempo. La brasa es ideal para cortes gruesos.
	    
	</p>

      </div>

</ul>
  
  
<p><a href="#">Lee más Preguntas Frecuentes (FAQ) en nuestro Centro de ayuda</a></p>
  </div>
   {% endblock %}

homepage/templates/homepage/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark" id="mainNav">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}"
      >
    <p>Cocina carnivora</p>
    </a>
      {% if user.is_authenticated %}
      <div class="bg-dark text-light text-uppercase ms-4 ">
        <a class="nav-link" href="#services"><i class="fa-solid fa-user me-2"></i>{{user.username}}</a>
      </div>
     {% endif %}
 
     <button
    class="navbar-toggler cerrar"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#navbarResponsive"
    aria-controls="navbarResponsive"
    aria-expanded="false"
    aria-label="Toggle navigation"
    >
    <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto py-4 py-lg-0">
        {% if user.is_authenticated %}
         
          
          {% if 'Dueño' in role %}
	       <li class="nav-item">
	       <a class="nav-link" href="{% url 'get_recipes' %}">Ver recetas</a>
            </li>
        
	  <li class="nav-item">
              <a class="nav-link" href="{% url 'create_recipe' %}">Crear receta</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#"></a>
          </li> 
	  {% endif %}
         
          {% if 'Invitado' in role %}
	       <li class="nav-item">
	       <a class="nav-link" href="{% url 'get_recipes' %}">Ver recetas</a>
            </li>

          <li class="nav-item">
            <a class="nav-link" href="#"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"
            >Registrar perro</a>
          </li>
          {% endif %}  

            <!-- <li class="nav-item">
              <a class="nav-link" href="{% url 'create_recipe' %}">Crear receta</a>
            </li> -->
    
            
            
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Ver perfil 
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'useraccount:editpro' %}">Editar cuenta</a></li>
            <li><a class="dropdown-item" href="{% url 'useraccount:password' %}">Cambiar password</a></li>
            <li><a class="dropdown-item" href="{% url 'useraccount:editprofile' user.id %}">Editar Perfil</a></li>
              
          </ul>
        </li>
        
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'useraccount:logout' %}"><i class="fa-solid fa-arrow-right-from-bracket pe-2"></i>Salir</a>
        </li>
        
        
        
        {% else %}
        
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'get_recipes' %}">Ver recetas</a>
        </li>
       <li class="nav-item">
          <a class="nav-link" href="{% url 'useraccount:register' %}">Registrarme</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'useraccount:login' %}">Iniciar sesión</a>
        </li>
        {% comment %} <li class="nav-item">
          <a class="nav-link" href="{% url 'create_recipe' %}">Crear receta</a>
        </li> {% endcomment %}
        {% endif %}
      </ul>
    </div>
  </div>
 
<script>
  $(document).click(function (event) {

  /// If *navbar-collapse* is not among targets of event
  if (!$(event.target).is('.navbar-collapse')) {

    /// Collapse every *navbar-collapse*
    $('.navbar-collapse').collapse('hide');

  }
}); 
</script>
  <script src="https://kit.fontawesome.com/ef04847ec0.js" crossorigin="anonymous"></script>
</nav>